services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 15
    ports: ["5432:5432"]

  bot:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: ["/app/entrypoint.sh"]
    volumes:
      - ./app:/app/app

volumes:
  pgdata:
